### ISSUE TITLE
Uncaught Error: Unknown provider: $rootScope from app 

### ISSUE THREAD

**Issue by drozzy** [mbrio/angular-authentication#3]
OOOPS: I meant to file this against your clone of `angular-http-auth`!
I get the `Uncaught Error: Unknown provider: $rootScope from app` error... It seems that dependency does not get injected during config.
Or am I doing something wrong?

**Comment by drozzy** [comment]
Well, your clone of `angular-http-auth` doesn't have issues :-(

**Comment by drozzy** [comment]
Indeed. You cannot have access to services in config block... See: http://stackoverflow.com/questions/10486769/cannot-get-to-rootscope

**Comment by mbrio** [comment]
Thanks drozzy, I'll look into this tomorrow.

**Comment by mbrio** [comment]
Are you still having problems with this? I can't seem to replicate the problem. What versions are you using?

**Comment by drozzy** [comment]
Sorry been a while. I don't remember ;-( But you can close it, when I get back to my project and if I encounter it again I'll reopen.

**Comment by mbrio** [comment]
Thanks drozzy, I'll be getting back to the project I built this for in about 3 weeks. I'm planning on folding my angular-http-auth implementation into this project so there is no reliance on external libraries.
