### ISSUE TITLE
Naming of "principal" and "authority"

### ISSUE THREAD

**Issue by Narretz** [mbrio/angular-authentication#4]
I find the naming a little "off". The common meaning of "principal" is "headmaster (of a school)" and "authority" is "The power to enforce laws, exact obedience, command, determine, or judge", and I haven't encountered these terms in regard to security yet.
I don't mean it cannot mean what you want it to mean, but I suspect it's weird for native speakers. Did you translate it from another language?

I'd suggest "token" for principal, and "authenticationProvider" for authority; however, currently the authServiceProvider has a similar name. In function, it acts more like a listener though: the interceptor listens for authentication details, the provider authenticates, and the token represents the authenticated entity.

**Comment by Narretz** [comment]
There is also the matter of "authentication" vs "authorization". Usually, authentication only refers to the process of proving your identity to a service (e.g. logging in). Authorization is the process of allowing access to some resource based on your rights. For example, the difference between what a user account and an admin can do.
This is mixed up in the module.

**Comment by mbrio** [comment]
Hi Narretz,

Just writing a quick one back on this, I've been busy with other parts of the application. As for principal and authority, I've gotten these names from other APIs (more specifically ASP.NET, as my background is in C#), I'm pretty happy with principal and authority. As for authentication and authorization I'll think about this one.
