### ISSUE TITLE
authServiceProvider.identityKeys is incorrect - should be authorityProvider

### ISSUE THREAD

**Issue by martemas** [mbrio/angular-authentication#5]
In the code's comment you mentioned that identityKeys can be configured via authServiceProvider.identityKeys
...
      // principal
      // ---------
      // The authenticated entity, it's identity object is dynamically
      // generated when authentication is successful. It's properties are
      // generated by looping through the data that was returned by the
      // authentication API using the white list of property values that can
      // be configured through `authServiceProvider.identityKeys`.
...

This should be `authorityProvider` as authServiceProvider is part of http-auth-interceptor.

**Comment by mbrio** [comment]
Good, eye! Fixed.
